apiVersion: v1
kind: Service
metadata:
  name: ems-backend-service
spec:
  selector:
    app: ems-backend
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Optional: can be omitted to let Kubernetes assign one automatically
